### ISSUE TITLE
Documentation on how CONFIG dictionary is built.

### ISSUE THREAD

**Issue by pdelboca** [datopian/giftless#65] opened 2021-01-18 16:05 UTC
The current logic to override giftless default configuration with the custom one in the `.yaml` file overrides the default configuration dictionary **only if** the same key exist in the `.yaml` file. Is that the desired behaviour or a buggy one? 

For example if I have a .yaml file with the following config spec:
```
PRE_AUTHORIZED_ACTION_PROVIDER:
 options:
   private_key: my-new-private-key
```
The final config will be:
```
"PRE_AUTHORIZED_ACTION_PROVIDER": {​
 'factory': 'giftless.auth.jwt:factory',
 'options': {​
 'algorithm': 'HS256',
 'private_key': 'my-new-private-key',
 'private_key_file': None,
 'public_key': None,
 'public_key_file': None,
 'default_lifetime': 60, # 60 seconds for default actions
 'key_id': 'giftless-internal-jwt-key',
 }​
 }​,
```
I may expect (IMHO), the `options` element to be identical as the one in my `.yaml` file and not a mix of both since it is not clear why all the other values are there (for example `key_id`).

**Comment by shevron** [comment] 2021-01-19 10:31
It's the expected behavior right now, although it may not be perfect and we can discuss it. 

Basically, configuration is merged on top of the default config (and on top of that, additional sources such as ENV vars or command line arguments may be merged). Dictionaries are merged and not replaced, unless the base config explicitly expects it. This is based on an old 3rd party config management library I wrote called [`figcan`](https://pypi.org/project/figcan/) but TBH I never felt it was a perfect solution (just a very simplistic one, which is good until proven otherwise). 

About this specific case, I'm not convinced it's a problem. All the default keys that are there are "for internal use", I don't think users should be bothered about them. We *can* improve it in some ways, e.g. by making the base  value for `PRE_AUTHORIZED_ACTION_PROVIDER.options` and `factory` be empty, and have "fallback" mechanism to use a 2nd set of options only if the 1st one has not been defined. But that means, that users will *need* to set things like `algorithm` and `key_id` (which is required, you just normally don't care about it's value). So I'm not sure this is a bad thing to keep it as is.

**Comment by shevron** [comment] 2021-03-02 10:48
I've updated the configuration section in the docs with more info. I'm not sure how to document this specific behavior, but since I've answered the question I'm going to close this ticket for now.

**Closed by shevron** 2021-03-02 10:48 UTC
Labels: documentation, enhancement, question
